// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Schema de PostgreSQL según entorno — mismo criterio que lib/prisma.ts
const DB_SCHEMA = process.env.DB_SCHEMA ?? 'public'
const baseUrl = process.env["DATABASE_URL"] ?? ''
const datasourceUrl = baseUrl.includes('?')
  ? `${baseUrl}&schema=${DB_SCHEMA}`
  : `${baseUrl}?schema=${DB_SCHEMA}`

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: datasourceUrl,
  },
});
