// Mapeo de marcas FASECOLDA (uppercase) → marcas canónicas BuscaCarro
export const FASECOLDA_BRAND_MAP: Record<string, string> = {
  CHEVROLET: 'Chevrolet',
  TOYOTA: 'Toyota',
  RENAULT: 'Renault',
  MAZDA: 'Mazda',
  KIA: 'Kia',
  HYUNDAI: 'Hyundai',
  FORD: 'Ford',
  NISSAN: 'Nissan',
  VOLKSWAGEN: 'Volkswagen',
  SUZUKI: 'Suzuki',
  HONDA: 'Honda',
  MITSUBISHI: 'Mitsubishi',
  JEEP: 'Jeep',
  DODGE: 'Dodge',
  BMW: 'BMW',
  'MERCEDES BENZ': 'Mercedes-Benz',
  AUDI: 'Audi',
  VOLVO: 'Volvo',
  PEUGEOT: 'Peugeot',
  FIAT: 'Fiat',
  SUBARU: 'Subaru',
  'LAND ROVER': 'Land Rover',
  ISUZU: 'Isuzu',
  CHERY: 'Chery',
  JAC: 'JAC',
  'GREAT WALL': 'Great Wall',
  'DFSK/DFM/DFZL': 'DFSK',
  GEELY: 'Geely',
  BYD: 'BYD',
  MG: 'MG',
  'SSANGYONG/KGM': 'SsangYong',
  INFINITI: 'Infiniti',
  ACURA: 'Acura',
  LEXUS: 'Lexus',
  PORSCHE: 'Porsche',
  'ALFA ROMEO': 'Alfa Romeo',
  CHRYSLER: 'Chrysler',
  HAVAL: 'Haval',
  CITROEN: 'Citroen',
  SKODA: 'Skoda',
  SEAT: 'Seat',
  MINI: 'Mini',
  RAM: 'Ram',
  TESLA: 'Tesla',
  CUPRA: 'Cupra',
  DS: 'DS',
  BAIC: 'Baic',
  CHANGAN: 'Changan',
  GAC: 'GAC',
  MAXUS: 'Maxus',
  JETOUR: 'Jetour',
  BAJAJ: 'Bajaj',
}

// Mapa inverso: marca canónica BuscaCarro → marca FASECOLDA
export const BUSCACARRO_TO_FASECOLDA: Record<string, string> = Object.fromEntries(
  Object.entries(FASECOLDA_BRAND_MAP).map(([fasecolda, buscacarro]) => [buscacarro, fasecolda])
)
